"""Harness Tool core protocol package."""

from __future__ import annotations

from .core import (
    CORE_BOUNDARIES,
    CORE_EXTENSION_POINTS,
    CORE_PROTOCOL_VERSION,
    CORE_STAGE_SEQUENCE,
    CONTRACT_STAGE,
    DISCOVERY_STAGE,
    SUGGEST_STAGE,
    VALIDATE_STAGE,
    ContractRules,
    ModuleContext,
    ScaffoldPlan,
    ValidationResult,
    apply_harness,
    build_apply_plan,
    build_contract_rules,
    build_init_plan,
    build_module_context,
    describe_core_boundaries,
    describe_development_guidance,
    describe_extension_guidance,
    init_module,
    load_profile_rules,
    normalize_relpath,
    validate_module,
)
from .markers import (
    CORE_MARKER_KEYS,
    DEFAULT_RECOMMENDED_MARKER_KEYS,
    DEFAULT_REQUIRED_MARKER_KEYS,
    MarkerRule,
    build_marker_registry,
    describe_marker_registry,
    render_marker_section,
)
from .rendering import (
    render_apply_smoke_test,
    render_changelog_document,
    render_default_config,
    render_index_document,
    render_init_entry_stub,
    render_init_smoke_test,
    render_spec_document,
    render_template_text,
)

__all__ = [
    "CORE_BOUNDARIES",
    "CORE_EXTENSION_POINTS",
    "CORE_MARKER_KEYS",
    "CORE_PROTOCOL_VERSION",
    "CORE_STAGE_SEQUENCE",
    "CONTRACT_STAGE",
    "DEFAULT_RECOMMENDED_MARKER_KEYS",
    "DEFAULT_REQUIRED_MARKER_KEYS",
    "DISCOVERY_STAGE",
    "SUGGEST_STAGE",
    "VALIDATE_STAGE",
    "ContractRules",
    "MarkerRule",
    "ModuleContext",
    "ScaffoldPlan",
    "ValidationResult",
    "apply_harness",
    "build_apply_plan",
    "build_contract_rules",
    "build_init_plan",
    "build_marker_registry",
    "build_module_context",
    "describe_core_boundaries",
    "describe_development_guidance",
    "describe_extension_guidance",
    "describe_marker_registry",
    "init_module",
    "load_profile_rules",
    "normalize_relpath",
    "render_apply_smoke_test",
    "render_changelog_document",
    "render_default_config",
    "render_index_document",
    "render_init_entry_stub",
    "render_init_smoke_test",
    "render_marker_section",
    "render_spec_document",
    "render_template_text",
    "validate_module",
]
